### ISSUE TITLE
Extra zeros in previous version

### ISSUE THREAD

**Issue by sjakobi** [kowainik/policeman#53]
I ran `policeman` in [this repo](https://github.com/sjakobi/newtype-generics):

```
$ policeman
⚙  curl --silent 'http://hackage.haskell.org/package/newtype-generics/newtype-generics-0.5.4.tar.gz' --output .policeman-evidence/newtype-generics-0.5.4.tar.gz
⚙  tar -xf .policeman-evidence/newtype-generics-0.5.4.tar.gz -C .policeman-evidence
⚙  cabal clean
⚙  cabal v2-build '--ghc-options=-fwrite-ide-info' '--ghc-options=-hiedir=.hie' '--verbose=0'
⚙  cabal clean
⚙  cabal v2-build '--ghc-options=-fwrite-ide-info' '--ghc-options=-hiedir=.hie' '--verbose=0'
  Deleted modules:
    Control.Newtype
  Per module diff:

🔄 Type of change:        Major
👵 Previous version:      0.5.4.0
💎 Suggested new version: 0.6.0.0
```

Note that the downloaded tarball has v0.5.4, but the output at the end mentions a nonexistent v0.5.4.0.

---

Thanks for creating this tool BTW! I really look forward to using it once wibbles like #52 have been straightened out! :)

**Comment by sjakobi** [comment]
(The version I used is v0.0.0.0 from Hackage.)

**Comment by chshersh** [comment]
@sjakobi Thanks for using the tool and providing your feedback! 😊 Yes, we thought about this use case and all machinery for this is already implemented. This can be fixed by changing a single line: just replacing `versionToText` with [`versionText`](https://github.com/kowainik/policeman/blob/a095eceb793ecc6858e1054f4f15ff40cbe1a5b8/src/Policeman/Core/Version.hs#L32) here

https://github.com/kowainik/policeman/blob/a095eceb793ecc6858e1054f4f15ff40cbe1a5b8/src/Policeman/Diff.hs#L75

PRs are welcome!
